config/routes.rb
Rails.application.routes.draw do
  
  #####################public側##################
  
  #devise
   devise_for :customers, controllers: {
    registrations: 'public/registrations',
    sessions:      'public/sessions'
  }
  
  scope module: :public do
    resources :addresses, only: [:index, :edit, :create, :update, :destroy] #address
    resources :orders, only: [:index, :create, :show, :new] #order
    resources :cart_items, only: [:index, :update, :destroy, :create] #cart_item
    resource :customers, only: [:edit, :update] #customer
    resources :items, only: [:index, :show] #item
  end
  
  #order
  post '/orders/confirm' => 'public/orders#confirm', as: 'confirm_order'
  get '/orders/complete' => 'public/orders#complete', as: 'complete_order'
  
  #cart_item
  delete '/cart_items/destroy_all' => 'public/cart_items#destroy_all', as: 'destroy_all_cart_item'
  
  #customer
  get '/customers/unsubscribe' => 'public/customers#unsubscribe', as: 'unsubscribe_customer'
  patch '/customers/withdraw' => 'public/customers#withdraw', as: 'withdraw_customer'
  get '/customers/my_page' => 'public/customers#show', as: 'customer_mypage'
  
  #homes
  get '/about' => 'public/homes#about', as: 'about_page'
  
  #root
  root to: 'public/homes#top'
  
  ###################################admin側########################
  
  #devise
  devise_for :admins, path: 'admin', controllers: {
    sessions:      'admin/sessions'
  }
  
  namespace :admin do
    resources :order_details, only: [:update] #order_details
    resources :orders, only: [:show, :update] #order
    resources :customers, only: [:index, :show, :edit, :update] #customer
    resources :genres, only: [:index, :create, :edit, :update] #genre
    resources :items, only: [:index, :new, :edit, :create, :show, :update] #item
  end
  
  #homes
  get '/admin' => 'admin/homes#top', as: 'admin_home'
  
end

app/models/address.rb
class Address < ApplicationRecord
  
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable,# :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses
  has_many :cart_items
  has_many :orders
  
  def full_name
    self.last_name + " " + self.first_name
  end
  
  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  
  attachment :image
  
  has_many :cart_items
  has_many :order_details
  belongs_to :genre
  
  def add_tax_price
    (self.price * 1.10).round
  end
end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :customer
  has_many :order_details
  
  enum payment_method: { credit_card: 0, bank: 1 }

  enum status: {
    waiting_for_payment: 0,
    payment_confirmation: 1,
    in_production: 2,
    preparing_to_ship: 3,
    sent: 4
  }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  
  belongs_to :item
  belongs_to :order
  
  enum making_status: {
    cannot_be_manufactured: 0,
　　waiting_for_production: 1, 
    in_production: 2,
    production_completed: 3,
  }
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
layout "admin"

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
layout "admin"

  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
layout "admin"  
  
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end
  
  private
  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
layout "admin"

  def show
  end

  def update
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  layout "admin"
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_home_path          #pathは設定したい遷移先へのpathを指定してください
    when Customer
      root_path              #ここもpathはご自由に変更してください
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      new_admin_session_path
    elsif resource_or_scope == :customer
      root_path
    else
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/create.html.erb
<h1>Admin::Genres#create</h1>
<p>Find me in app/views/admin/genres/create.html.erb</p>

app/views/admin/genres/edit.html.erb
<div class="container">
  <h5><span>ジャンル編集</span></h5>
  <div class="row">
    <div class="col-sm-9 col-md-8 col-lg-6 ">
      <%= form_with model: @genre, url: "/admin/genres/#{@genre.id}", local: true do |f| %>
        <%= f.label :ジャンル名 %>
        <%= f.text_field :name, autofocus: true %>
        <%= f.submit "変更を保存", class: "btn btn-outline-success btn-sm" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <h5><span>ジャンル一覧・追加</span></h5>
    <div class="row">
      <div class="col-sm-9 col-md-8 col-lg-6 ">

        <%= form_with model: @genre, url:'/admin/genres', local: true do |f| %>
          <div class="field">
            <%= f.label :ジャンル名 %>
            <%= f.text_field :name, autofocus: true %>
            <%= f.submit '新規登録', class: "btn btn-outline-success btn-sm " %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6 col-md-8 col-lg-6 ">
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th colspan="2">ジャンル</td>
            </tr>
          </thead>
    
          <tbody>
            <% @genres.each do |genre| %>
              <tr>
                <td><%= genre.name %></td>
                <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-outline-success btn-sm" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

</div>

app/views/admin/genres/update.html.erb
<h1>Admin::Genres#update</h1>
<p>Find me in app/views/admin/genres/update.html.erb</p>

app/views/admin/items/edit.html.erb
<div class="container">
  <h5><span>商品編集</span></h5>

<%= form_with model: @item, url: "/admin/items/#{@item.id}", local: true do |f| %>
  <div class="row">
    <div class="col-sm-4 col-md-3 col-lg-3">
      <%= f.label :商品画像 %>
    </div>
    <div class="col-sm-8 col-md-9 col-lg-9">
      <%= f.attachment_field :image %>
    </div>
  </div>
  
  <div class="row">
    <div class="col-sm-4 col-md-3 col-lg-3">
      <%= f.label :商品名 %>
    </div>
    <div class="col-sm-8 col-md-9 col-lg-9">
      <%= f.text_field :name, size: 45, autofocus: true, placeholder: "商品名" %>
    </div>
  </div>
  
  
  <div class="row">
    <div class="col-sm-4 col-md-3 col-lg-3">
      <%= f.label :商品説明 %>
    </div>
    <div class="col-sm-8 col-md-9 col-lg-9">
      <%= f.text_area :introduction, size: "10x4", class: "form-control", placeholder: "ここに説明文を記述します" %>
    </div>
  </div>
  
  <div class="row">
    <div class="col-sm-4 col-md-3 col-lg-3">
      <%= f.label :ジャンル %>
    </div>
    <div class="col-sm-8 col-md-9 col-lg-9">
      <%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: "選択してください" %>
    </div>
  </div>
  
  <div class="row">
    <div class="col-sm-4 col-md-3 col-lg-3">
      <%= f.label :税抜き価格 %>
    </div>
    <div class="col-sm-8 col-md-9 col-lg-9">
      <%= f.number_field :price, placeholder: 1000 %>円
    </div>
  </div>
  
  <div class="row">
    <div class="col-sm-4 col-md-3 col-lg-3">
      <%= f.label :販売ステータス %>
    </div>
    <div class="col-sm-8 col-md-9 col-lg-9">
      <%= f.radio_button :is_active, true %>
      <%= f.label :is_active, '販売中', value: true %>
      <%= f.radio_button :is_active, false %>
      <%= f.label :is_active, '販売停止中', value: false %>
    </div>
  </div>
  
  <div class="center">
    <%= f.submit '変更を保存', class: "btn btn-outline-success btn-sm" %>
  </div>

<% end %>

</div>

app/views/admin/items/index.html.erb
<div class="container">
  <h5>
    <span>
      商品一覧
    </span>
    <%= link_to new_admin_item_path, class: 'fas fa-plus-circle nav-link text-dark' do %><% end %>
    </h5>
  
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 ">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          <tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
              <tr>
                <td><%= item.id %></td>
                <td>
                  <%= link_to admin_item_path(item.id) do %>
                    <%= item.name %>
                  <% end %>
                </td>
                <td><%= item.price %></td>
                <td><%= item.genre.name %></td>
                <td><%= item.is_active ? '販売中' : '販売停止中' %></td>
              <tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>


</div>

app/views/admin/items/new.html.erb
<h2>
  商品新規登録
</h2>

<%= form_with model: @item, url:'/admin/items', local: true do |f| %>
  <div class ="form-group">
    <%= f.label :商品画像 %>
    <%= f.attachment_field :image %>
  </div>
  <div class ="form-group">
    <%= f.label :商品名 %>
    <%= f.text_field :name, autofocus: true, placeholder: "商品名" %>
  </div>
  <div class="form-group">
    <%= f.label :商品説明 %>
    <%= f.text_area :introduction, placeholder: "ここに説明文を記述します" %>
  </div>
  <div class ="form-group">
    <%= f.label :ジャンル %>
    <%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: "選択してください" %>
  </div>
  <div class ="form-group">
    <%= f.label :税抜き価格 %>
    <%= f.text_field :price, placeholder: 1000 %>円
  </div>
  <div class ="form-group">
    <%= f.label :販売ステータス %>
    <div>
      <%= f.radio_button :is_active, true %>
      <%= f.label :is_active, '販売中', value: true %>
    </div>
    <div>
      <%= f.radio_button :is_active, false %>
      <%= f.label :is_active, '販売停止中', value: false %>
    </div>
  </div>
  <div class="form-group">
    <%= f.submit "新規登録" %>
  </div>

<% end %>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <h5><span>商品詳細</span></h5>
  </div>
  <div class="row">
    <div class="col-sm-5 col-md-5 col-lg-4">
      <%= attachment_image_tag @item, :image, size: "300x300", format: 'jpeg' %>
    </div>
    <div class="margin col-sm-7 col-md-7 col-lg-8 ">
      
      <div class="row">
        <div class="col-sm-4 col-lg-3">
          <h6>商品</h6>
        </div>
        <div class="col-sm-8 col-lg-9">
          <%= @item.name %>
        </div>
      </div>
      
      <div class="row">
        <div class="col-sm-4 col-lg-3">
          <h6>商品説明</h6>
        </div>
        <div class="col-sm-8 col-lg-9">
          <%= @item.introduction %>
        </div>
      </div>
      
      <div class="row">
        <div class="col-sm-4 col-lg-3">
          <h6>ジャンル</h6>
        </div>
        <div class="col-sm-8 col-lg-9">
          <%= @item.genre.name %>
        </div>
      </div>
      
      <div class="row">
        <div class="col-sm-4 col-lg-3">
          <h6>税込価格(税抜価格)</h6>
        </div>
        <div class="col-sm-8 col-lg-9">
          <%= @item.add_tax_price.to_s(:delimited) %> (<%= @item.price.to_s(:delimited) %>) 円
        </div>
      </div>
      
      <div class="row">
        <div class="col-sm-4 col-lg-3">
          <h6>販売ステータス</h6>
        </div>
        <div class="col-sm-8 col-lg-9">
          <%= @item.is_active ? '販売中' : '販売' %>
        </div>
      </div>
      
      
      <div class="center">
        <%= link_to edit_admin_item_path(@item.id), class: "btn btn-outline-success btn-sm" do %>編集する<% end %>
      </div>
      
      
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <h2>注文履歴詳細</h2>
    <div class="row">
      <div class="col-md-2">
        <h3>購入者</h3>
        <h3>注文日</h3>
        <h3>配送先</h3>
        <h3>支払方法</h3>
        <h3>注文ステータス</h3>
      </div>
      <div class="col-md-10">
        <h3><%= @order.customer.full_name %></h3>
        <h3><%= @order.created_at %></h3>
        <h3><%= @order.postal_code %><%= @customer.address %></h3>
        <h3><%= @order.payment_method_i18n %></h3>
        <% form_with model: @order, url: "/admin/orders/#{@order.id}" do |f| %>
        <h3><%= f.select :status, Order.statuses_i18n.keys.map {|k| [I18n.t("enum.order.status.#{k}"), k]} %></h3> 
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-8">
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>商品名</th>
              <th>単価(税込)</th>
              <th>数量</th>
              <th>小計</th>
              <th>製作ステータス</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @order_details.each do |p| %>
            <tr>
              <td><%= p.item.name</td>
              <td><%= p.price.to_s(:delimited) %></td>
              <td><%= p.amount %></td>
              <td><%= p.price * p.amount.to_s(:delimited) %></td>
              <% form_with p, url: "admin/order_details/#{p.id}" do |f| %>
              <td><%= f.select :making_status, OrderDetail.making_statuses_i18n.keys.map {|k| [I18n.t("enum.orderdetail.status.#{k}"), k]} %></td>
              <td><%= f.submit '更新', class: "btn btn-primary" %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="col-md-2">
        <h3>商品合計</h3>
        <h3>送料</h3>
        <h3>請求金額合計</h3>
      </div>
      <div class="col-md-2">
        <h3><%= @order.total_payment - @order.shipping_cost %>円</h3>
        <h3><%= @order.shipping_cost %>円</h3>
        <h3><%= @order.total_payment %>円</h3>
      </div>
    </div>
</div>

app/views/admin/orders/update.html.erb
<h1>Admin::Orders#update</h1>
<p>Find me in app/views/admin/orders/update.html.erb</p>