config/routes.rb
Rails.application.routes.draw do
  
  #####################public側##################
  
  #devise
   devise_for :customers, controllers: {
    registrations: 'public/registrations',
    sessions:      'public/sessions'
  }
  
  scope module: :public do
    resources :addresses, only: [:index, :edit, :create, :update, :destroy] #address
    resources :orders, only: [:index, :create, :show, :new] #order
    resources :cart_items, only: [:index, :update, :destroy, :create] #cart_item
    resource :customers, only: [:edit, :update] #customer
    resources :items, only: [:index, :show] #item
  end
  
  #order
  post '/orders/confirm' => 'public/orders#confirm', as: 'confirm_order'
  get '/orders/complete' => 'public/orders#complete', as: 'complete_order'
  
  #cart_item
  delete '/cart_items/destroy_all' => 'public/cart_items#destroy_all', as: 'destroy_all_cart_item'
  
  #customer
  get '/customers/unsubscribe' => 'public/customers#unsubscribe', as: 'unsubscribe_customer'
  patch '/customers/withdraw' => 'public/customers#withdraw', as: 'withdraw_customer'
  get '/customers/my_page' => 'public/customers#show', as: 'customer_mypage'
  
  #homes
  get '/about' => 'public/homes#about', as: 'about_page'
  
  #root
  root to: 'public/homes#top'
  
  ###################################admin側########################
  
  #devise
  devise_for :admins, path: 'admin', controllers: {
    sessions:      'admin/sessions'
  }
  
  namespace :admin do
    resources :order_details, only: [:update] #order_details
    resources :orders, only: [:show, :update] #order
    resources :customers, only: [:index, :show, :edit, :update] #customer
    resources :genres, only: [:index, :create, :edit, :update] #genre
    resources :items, only: [:index, :new, :edit, :create, :show, :update] #item
  end
  
  #homes
  get '/admin' => 'admin/homes#top', as: 'admin_home'
  
end

app/models/address.rb
class Address < ApplicationRecord
  
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable,# :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses
  has_many :cart_items
  has_many :orders
  
  def full_name
    self.last_name + " " + self.first_name
  end
  
  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  
  attachment :image
  
  has_many :cart_items
  has_many :order_details
  belongs_to :genre
  
  def add_tax_price
    (self.price * 1.10).round
  end
end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :customer
  has_many :order_details
  
  enum payment_method: { credit_card: 0, bank: 1 }

  enum status: {
    waiting_for_payment: 0,
    payment_confirmation: 1,
    in_production: 2,
    preparing_to_ship: 3,
    sent: 4
  }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  
  belongs_to :item
  belongs_to :order
  
  enum making_status: {
    cannot_be_manufactured: 0,
　　waiting_for_production: 1, 
    in_production: 2,
    production_completed: 3,
  }
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
layout "admin"

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
layout "admin"

  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
layout "admin"  
  
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end
  
  private
  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_home_path          #pathは設定したい遷移先へのpathを指定してください
    when Customer
      root_path              #ここもpathはご自由に変更してください
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      new_admin_session_path
    elsif resource_or_scope == :customer
      root_path
    else
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake:管理者画面</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e6e6fa;">
        <div class="container">
          <a class="navbar-brand p-1" href="/"><span>nagano cake --admin--</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %>
                <li>
                  <%= link_to admin_items_path, class: 'fas fa-home nav-link text-dark' do %>商品一覧<% end %>
                </li>
                <li>
                  <%= link_to admin_customers_path, class: 'fas fa-home nav-link text-dark' do %>会員一覧<% end %>
                </li>
                <li>
                  <%= link_to admin_home_path, class: 'fas fa-home nav-link text-dark' do %>注文履歴一覧<% end %>
                </li>
                <li>
                  <%= link_to admin_genres_path, class: 'fas fa-home nav-link text-dark' do %>ジャンル一覧<% end %>
                </li>
                <li>
                  <%= link_to destroy_admin_session_path, method: :delete, class: 'fas fa-home nav-link text-dark' do %>ログアウト<% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to 'About', about_page_path, class: 'fas fa-home nav-link text-dark' %>
                </li>
                <li>
                  <%= link_to items_path, class: 'fas fa-home nav-link text-dark' do %>商品一覧<% end %>
                </li>
                <li>
                  <%= link_to new_customer_registration_path, class: 'fas fa-home nav-link text-dark' do %>新規登録<% end %>
                </li>
                <li>
                  <%= link_to new_customer_session_path, class: 'fas fa-home nav-link text-dark' do %>ログイン<% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="main">
      <p id="notice"></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-4" href="/">nagano ケーキ</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="nav-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if customer_signed_in? %>
                <li>
                  <%= link_to admin_items_path do %>商品一覧<% end %>
                </li>
                <li>
                  <%= link_to admin_customers_path do %>会員一覧<% end %>
                </li>
                <li>
                  <%= link_to admin_home_path do %>注文履歴一覧<% end %>
                </li>
                <li>
                  <%= link_to admin_genres_path do %>ジャンル一覧<% end %>
                </li>
                <li>
                  <%= link_to destroy_admin_session_path do %>管理者サインアウト<% end %>
                </li>
                <li>
                  <%= link_to destroy_customer_session_path, method: :delete do %>会員サインアウト<% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to about_page_path do %>About<% end %>
                </li>
                <li>
                  <%= link_to admin_items_path do %>商品一覧<% end %>
                </li>
                <li>
                  <%= link_to new_customer_registration_path do %>新規登録<% end %>
                </li>
                <li>
                  <%= link_to new_customer_session_path do %>ログイン<% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>